### ISSUE TITLE
Tooltips on mouse hover over buttons do not show (some users)

### ISSUE THREAD

**Issue by antobenve** [unep-grid/mapx#958] opened 2023-11-01 10:17 UTC
During yesterday's training, I had feedbacks from some users about tooltips not showing in MapX (navigation panel and views' panel at least).

The users that reported this issue could never display the tooltips no matter the solution tested (Firefox and Chrome (also incognito) in Windows 10). 

To investigate

**Comment by thomaspiller** [comment] 2024-05-22 13:24
@antobenve I've done some testing on MacOS and Windows (Chrome & Firefox) and can't seem to reproduce this bug. Has anyone else managed to reproduce it? If not, I suggest closing the issue for now.

**Comment by thomaspiller** [comment] 2024-09-25 15:11
I am closing this issue as it has not been mentioned in recent months and I am unable to reproduce this bug.

**Closed by thomaspiller** 2024-09-25 15:11 UTC
Labels: bug, priority 2, Investigating
